name: Node.js Docker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️⃣ Set up Node.js (optional, if you need npm scripts)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # 3️⃣ Build Docker image
    - name: Build Docker image
      run: |
        docker build -t node-todo-app .

    # 4️⃣ Run container for testing
    - name: Run container
      run: |
        docker run -d --name todo-test -p 3000:3000 node-todo-app
        sleep 10  # wait for server to start

    # 5️⃣ Test container is responding
    - name: Check container response
      run: |
        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000)
        echo "Response code: $RESPONSE"
        if [ "$RESPONSE" -ne 200 ]; then
          echo "App did not start correctly"
          exit 1
        fi

    # 6️⃣ Stop and remove container
    - name: Cleanup
      run: |
        docker stop todo-test
        docker rm todo-test
